//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SABSyncModel", "FK_episodes_0", "shows", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SABSync.Web.shows), "episodes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SABSync.Web.episodes), true)]
[assembly: EdmRelationshipAttribute("SABSyncModel", "FK_histories_0", "episodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SABSync.Web.episodes), "histories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SABSync.Web.histories), true)]
[assembly: EdmRelationshipAttribute("SABSyncModel", "FK_histories_1", "shows", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SABSync.Web.shows), "histories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SABSync.Web.histories), true)]

#endregion

namespace SABSync.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SABSyncEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SABSyncEntities object using the connection string found in the 'SABSyncEntities' section of the application configuration file.
        /// </summary>
        public SABSyncEntities() : base("name=SABSyncEntities", "SABSyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SABSyncEntities object.
        /// </summary>
        public SABSyncEntities(string connectionString) : base(connectionString, "SABSyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SABSyncEntities object.
        /// </summary>
        public SABSyncEntities(EntityConnection connection) : base(connection, "SABSyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<episodes> episodes
        {
            get
            {
                if ((_episodes == null))
                {
                    _episodes = base.CreateObjectSet<episodes>("episodes");
                }
                return _episodes;
            }
        }
        private ObjectSet<episodes> _episodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<histories> histories
        {
            get
            {
                if ((_histories == null))
                {
                    _histories = base.CreateObjectSet<histories>("histories");
                }
                return _histories;
            }
        }
        private ObjectSet<histories> _histories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<info> info
        {
            get
            {
                if ((_info == null))
                {
                    _info = base.CreateObjectSet<info>("info");
                }
                return _info;
            }
        }
        private ObjectSet<info> _info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<providers> providers
        {
            get
            {
                if ((_providers == null))
                {
                    _providers = base.CreateObjectSet<providers>("providers");
                }
                return _providers;
            }
        }
        private ObjectSet<providers> _providers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<shows> shows
        {
            get
            {
                if ((_shows == null))
                {
                    _shows = base.CreateObjectSet<shows>("shows");
                }
                return _shows;
            }
        }
        private ObjectSet<shows> _shows;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the episodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToepisodes(episodes episodes)
        {
            base.AddObject("episodes", episodes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the histories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohistories(histories histories)
        {
            base.AddObject("histories", histories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToinfo(info info)
        {
            base.AddObject("info", info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the providers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproviders(providers providers)
        {
            base.AddObject("providers", providers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the shows EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToshows(shows shows)
        {
            base.AddObject("shows", shows);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SABSyncModel", Name="episodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class episodes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new episodes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static episodes Createepisodes(global::System.Int64 id)
        {
            episodes episodes = new episodes();
            episodes.id = id;
            return episodes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> show_id
        {
            get
            {
                return _show_id;
            }
            set
            {
                Onshow_idChanging(value);
                ReportPropertyChanging("show_id");
                _show_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("show_id");
                Onshow_idChanged();
            }
        }
        private Nullable<global::System.Int64> _show_id;
        partial void Onshow_idChanging(Nullable<global::System.Int64> value);
        partial void Onshow_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> season_number
        {
            get
            {
                return _season_number;
            }
            set
            {
                Onseason_numberChanging(value);
                ReportPropertyChanging("season_number");
                _season_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("season_number");
                Onseason_numberChanged();
            }
        }
        private Nullable<global::System.Int64> _season_number;
        partial void Onseason_numberChanging(Nullable<global::System.Int64> value);
        partial void Onseason_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> episode_number
        {
            get
            {
                return _episode_number;
            }
            set
            {
                Onepisode_numberChanging(value);
                ReportPropertyChanging("episode_number");
                _episode_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("episode_number");
                Onepisode_numberChanged();
            }
        }
        private Nullable<global::System.Int64> _episode_number;
        partial void Onepisode_numberChanging(Nullable<global::System.Int64> value);
        partial void Onepisode_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String episode_name
        {
            get
            {
                return _episode_name;
            }
            set
            {
                Onepisode_nameChanging(value);
                ReportPropertyChanging("episode_name");
                _episode_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("episode_name");
                Onepisode_nameChanged();
            }
        }
        private global::System.String _episode_name;
        partial void Onepisode_nameChanging(global::System.String value);
        partial void Onepisode_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String air_date
        {
            get
            {
                return _air_date;
            }
            set
            {
                Onair_dateChanging(value);
                ReportPropertyChanging("air_date");
                _air_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("air_date");
                Onair_dateChanged();
            }
        }
        private global::System.String _air_date;
        partial void Onair_dateChanging(global::System.String value);
        partial void Onair_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> tvdb_id
        {
            get
            {
                return _tvdb_id;
            }
            set
            {
                Ontvdb_idChanging(value);
                ReportPropertyChanging("tvdb_id");
                _tvdb_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tvdb_id");
                Ontvdb_idChanged();
            }
        }
        private Nullable<global::System.Int64> _tvdb_id;
        partial void Ontvdb_idChanging(Nullable<global::System.Int64> value);
        partial void Ontvdb_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String overview
        {
            get
            {
                return _overview;
            }
            set
            {
                OnoverviewChanging(value);
                ReportPropertyChanging("overview");
                _overview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("overview");
                OnoverviewChanged();
            }
        }
        private global::System.String _overview;
        partial void OnoverviewChanging(global::System.String value);
        partial void OnoverviewChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_episodes_0", "shows")]
        public shows shows
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_episodes_0", "shows").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_episodes_0", "shows").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<shows> showsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_episodes_0", "shows");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<shows>("SABSyncModel.FK_episodes_0", "shows", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_histories_0", "histories")]
        public EntityCollection<histories> histories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<histories>("SABSyncModel.FK_histories_0", "histories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<histories>("SABSyncModel.FK_histories_0", "histories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SABSyncModel", Name="histories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class histories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new histories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static histories Createhistories(global::System.Int64 id)
        {
            histories histories = new histories();
            histories.id = id;
            return histories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> show_id
        {
            get
            {
                return _show_id;
            }
            set
            {
                Onshow_idChanging(value);
                ReportPropertyChanging("show_id");
                _show_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("show_id");
                Onshow_idChanged();
            }
        }
        private Nullable<global::System.Int64> _show_id;
        partial void Onshow_idChanging(Nullable<global::System.Int64> value);
        partial void Onshow_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> episode_id
        {
            get
            {
                return _episode_id;
            }
            set
            {
                Onepisode_idChanging(value);
                ReportPropertyChanging("episode_id");
                _episode_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("episode_id");
                Onepisode_idChanged();
            }
        }
        private Nullable<global::System.Int64> _episode_id;
        partial void Onepisode_idChanging(Nullable<global::System.Int64> value);
        partial void Onepisode_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String feed_title
        {
            get
            {
                return _feed_title;
            }
            set
            {
                Onfeed_titleChanging(value);
                ReportPropertyChanging("feed_title");
                _feed_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("feed_title");
                Onfeed_titleChanged();
            }
        }
        private global::System.String _feed_title;
        partial void Onfeed_titleChanging(global::System.String value);
        partial void Onfeed_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quality
        {
            get
            {
                return _quality;
            }
            set
            {
                OnqualityChanging(value);
                ReportPropertyChanging("quality");
                _quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quality");
                OnqualityChanged();
            }
        }
        private Nullable<global::System.Int32> _quality;
        partial void OnqualityChanging(Nullable<global::System.Int32> value);
        partial void OnqualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> proper
        {
            get
            {
                return _proper;
            }
            set
            {
                OnproperChanging(value);
                ReportPropertyChanging("proper");
                _proper = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("proper");
                OnproperChanged();
            }
        }
        private Nullable<global::System.Int64> _proper;
        partial void OnproperChanging(Nullable<global::System.Int64> value);
        partial void OnproperChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String provider
        {
            get
            {
                return _provider;
            }
            set
            {
                OnproviderChanging(value);
                ReportPropertyChanging("provider");
                _provider = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("provider");
                OnproviderChanged();
            }
        }
        private global::System.String _provider;
        partial void OnproviderChanging(global::System.String value);
        partial void OnproviderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_histories_0", "episodes")]
        public episodes episodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<episodes>("SABSyncModel.FK_histories_0", "episodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<episodes>("SABSyncModel.FK_histories_0", "episodes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<episodes> episodesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<episodes>("SABSyncModel.FK_histories_0", "episodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<episodes>("SABSyncModel.FK_histories_0", "episodes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_histories_1", "shows")]
        public shows shows
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_histories_1", "shows").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_histories_1", "shows").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<shows> showsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<shows>("SABSyncModel.FK_histories_1", "shows");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<shows>("SABSyncModel.FK_histories_1", "shows", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SABSyncModel", Name="info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new info object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static info Createinfo(global::System.Int64 id)
        {
            info info = new info();
            info.id = id;
            return info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> last_tvdb
        {
            get
            {
                return _last_tvdb;
            }
            set
            {
                Onlast_tvdbChanging(value);
                ReportPropertyChanging("last_tvdb");
                _last_tvdb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_tvdb");
                Onlast_tvdbChanged();
            }
        }
        private Nullable<global::System.Int64> _last_tvdb;
        partial void Onlast_tvdbChanging(Nullable<global::System.Int64> value);
        partial void Onlast_tvdbChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SABSyncModel", Name="providers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class providers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new providers object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static providers Createproviders(global::System.Int64 id)
        {
            providers providers = new providers();
            providers.id = id;
            return providers;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SABSyncModel", Name="shows")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class shows : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new shows object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static shows Createshows(global::System.Int64 id)
        {
            shows shows = new shows();
            shows.id = id;
            return shows;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String show_name
        {
            get
            {
                return _show_name;
            }
            set
            {
                Onshow_nameChanging(value);
                ReportPropertyChanging("show_name");
                _show_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("show_name");
                Onshow_nameChanged();
            }
        }
        private global::System.String _show_name;
        partial void Onshow_nameChanging(global::System.String value);
        partial void Onshow_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> tvdb_id
        {
            get
            {
                return _tvdb_id;
            }
            set
            {
                Ontvdb_idChanging(value);
                ReportPropertyChanging("tvdb_id");
                _tvdb_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tvdb_id");
                Ontvdb_idChanged();
            }
        }
        private Nullable<global::System.Int64> _tvdb_id;
        partial void Ontvdb_idChanging(Nullable<global::System.Int64> value);
        partial void Ontvdb_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tvdb_name
        {
            get
            {
                return _tvdb_name;
            }
            set
            {
                Ontvdb_nameChanging(value);
                ReportPropertyChanging("tvdb_name");
                _tvdb_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tvdb_name");
                Ontvdb_nameChanged();
            }
        }
        private global::System.String _tvdb_name;
        partial void Ontvdb_nameChanging(global::System.String value);
        partial void Ontvdb_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> quality
        {
            get
            {
                return _quality;
            }
            set
            {
                OnqualityChanging(value);
                ReportPropertyChanging("quality");
                _quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quality");
                OnqualityChanged();
            }
        }
        private Nullable<global::System.Int64> _quality;
        partial void OnqualityChanging(Nullable<global::System.Int64> value);
        partial void OnqualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ignore_season
        {
            get
            {
                return _ignore_season;
            }
            set
            {
                Onignore_seasonChanging(value);
                ReportPropertyChanging("ignore_season");
                _ignore_season = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ignore_season");
                Onignore_seasonChanged();
            }
        }
        private Nullable<global::System.Int32> _ignore_season;
        partial void Onignore_seasonChanging(Nullable<global::System.Int32> value);
        partial void Onignore_seasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aliases
        {
            get
            {
                return _aliases;
            }
            set
            {
                OnaliasesChanging(value);
                ReportPropertyChanging("aliases");
                _aliases = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aliases");
                OnaliasesChanged();
            }
        }
        private global::System.String _aliases;
        partial void OnaliasesChanging(global::System.String value);
        partial void OnaliasesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String air_day
        {
            get
            {
                return _air_day;
            }
            set
            {
                Onair_dayChanging(value);
                ReportPropertyChanging("air_day");
                _air_day = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("air_day");
                Onair_dayChanged();
            }
        }
        private global::System.String _air_day;
        partial void Onair_dayChanging(global::System.String value);
        partial void Onair_dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String air_time
        {
            get
            {
                return _air_time;
            }
            set
            {
                Onair_timeChanging(value);
                ReportPropertyChanging("air_time");
                _air_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("air_time");
                Onair_timeChanged();
            }
        }
        private global::System.String _air_time;
        partial void Onair_timeChanging(global::System.String value);
        partial void Onair_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> run_time
        {
            get
            {
                return _run_time;
            }
            set
            {
                Onrun_timeChanging(value);
                ReportPropertyChanging("run_time");
                _run_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("run_time");
                Onrun_timeChanged();
            }
        }
        private Nullable<global::System.Int64> _run_time;
        partial void Onrun_timeChanging(Nullable<global::System.Int64> value);
        partial void Onrun_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String poster_url
        {
            get
            {
                return _poster_url;
            }
            set
            {
                Onposter_urlChanging(value);
                ReportPropertyChanging("poster_url");
                _poster_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("poster_url");
                Onposter_urlChanged();
            }
        }
        private global::System.String _poster_url;
        partial void Onposter_urlChanging(global::System.String value);
        partial void Onposter_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String banner_url
        {
            get
            {
                return _banner_url;
            }
            set
            {
                Onbanner_urlChanging(value);
                ReportPropertyChanging("banner_url");
                _banner_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("banner_url");
                Onbanner_urlChanged();
            }
        }
        private global::System.String _banner_url;
        partial void Onbanner_urlChanging(global::System.String value);
        partial void Onbanner_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imdb_id
        {
            get
            {
                return _imdb_id;
            }
            set
            {
                Onimdb_idChanging(value);
                ReportPropertyChanging("imdb_id");
                _imdb_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imdb_id");
                Onimdb_idChanged();
            }
        }
        private global::System.String _imdb_id;
        partial void Onimdb_idChanging(global::System.String value);
        partial void Onimdb_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String genre
        {
            get
            {
                return _genre;
            }
            set
            {
                OngenreChanging(value);
                ReportPropertyChanging("genre");
                _genre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("genre");
                OngenreChanged();
            }
        }
        private global::System.String _genre;
        partial void OngenreChanging(global::System.String value);
        partial void OngenreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String overview
        {
            get
            {
                return _overview;
            }
            set
            {
                OnoverviewChanging(value);
                ReportPropertyChanging("overview");
                _overview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("overview");
                OnoverviewChanged();
            }
        }
        private global::System.String _overview;
        partial void OnoverviewChanging(global::System.String value);
        partial void OnoverviewChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_episodes_0", "episodes")]
        public EntityCollection<episodes> episodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<episodes>("SABSyncModel.FK_episodes_0", "episodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<episodes>("SABSyncModel.FK_episodes_0", "episodes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SABSyncModel", "FK_histories_1", "histories")]
        public EntityCollection<histories> histories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<histories>("SABSyncModel.FK_histories_1", "histories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<histories>("SABSyncModel.FK_histories_1", "histories", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
